name: example
description: "An example app for how to use the friends_badge package."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter: #
    sdk: flutter
  friends_badge: #
    path: ../
  image_picker: ^1.0.7
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.4

dev_dependencies:
  flame_lint: ^1.4.1

flutter:
  uses-material-design: true