name: example
description: "An example app for how to use the friends_badge package."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  friends_badge: ^0.1.2
  image: ^4.5.4
  image_picker: ^1.2.0

dev_dependencies:
  flame_lint: ^1.4.2

flutter:
  uses-material-design: true
