name: friends_badge
description: "Control the Flutter & Friends conference badge."
version: 0.1.2+1
repository: https://github.com/flutter-and-friends/friends_badge

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  image: ^4.5.4
  nfc_manager: ^4.0.2

dev_dependencies:
  flame_lint: ^1.4.2
  melos: ^7.1.0

melos:
  useRootAsPackage: true
  command:
    version:
      branch: main
      releaseUrl: true
      includeCommitId: true
      linkToCommits: true
      workspaceChangelog: false

  scripts:
    analyze:
      run: melos exec dart analyze .
      description: Run `dart analyze` for all packages.

    format-check:
      run: melos exec dart format . --set-exit-if-changed
      description: Run `dart format` checks for all packages.

    markdown-check:
      run: markdownlint . --ignore-path .markdownlintignore --config .markdownlint.yaml
      description: Runs the markdown linting check.

    markdown-fix:
      run: markdownlint . --fix --ignore-path .markdownlintignore --config .markdownlint.yaml
      description: Fixes the markdown linting errors.

    test:select:
      run: melos exec -c 1 -- flutter test
      packageFilters:
        dirExists: test
      description: Run `flutter test` for selected packages.

    test:
      run: melos run test:select --no-select
      description: Run all Flutter tests in this project.
