name: friends_badge
description: "Control the Flutter & Friends conference badge."
version: 0.1.0
repository: https://github.com/spydon/friends_badge

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.5"

dependencies:
  barcode_widget: ^2.0.4
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  image: ^4.5.4
  nfc_manager: ^4.0.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flame_lint: ^1.4.0