name: friends_badge
description: "Control the Flutter & Friends conference badge."
version: 0.1.0
repository: https://github.com/spydon/friends_badge

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.5"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
  flutter_blue_plus: ^1.31.16
  nfc_manager: ^3.4.0
  nfc_manager: ^3.4.0
  image: ^4.0.17
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4

dev_dependencies:
  flame_lint: ^1.4.0