import 'package:friends_badge/src/ndef/ndef.dart';

/// A decoded badge payload: the person's name, role, and any URLs found in
/// the Text record, plus the primary URI from the U record if present, plus
/// the optional tagged segments (`id:<installId>`, `capy:<assetName>`).
///
/// This is the shape `ff-pokedex-collect` consumes when collecting a person.
/// Decoding is deliberately tolerant: a missing U record, a missing T
/// record, or an unexpected payload shape degrade to empty/null fields
/// rather than throwing.
class BadgePerson {
  const BadgePerson({
    required this.name,
    required this.role,
    required this.urls,
    required this.primaryUri,
    required this.installId,
    required this.capybaraId,
  });

  /// Decode a badge [NdefMessage] into a [BadgePerson].
  ///
  /// The expected wire format (published by `friends-badge-ndef`, v2) is:
  ///
  /// ```
  /// [U record]  primary personal URL (e.g. LinkedIn)
  /// [T record]  "Name · Role · url1 · … · urlN · id:<installId>
  ///              · capy:<assetName>"
  /// ```
  ///
  /// The Text record is split on `" · "` (space, U+00B7 MIDDLE DOT, space):
  ///
  /// - segment 0 → [name]
  /// - segment 1 → [role] (may be the empty string)
  /// - segments 2..n → mixed: URLs, plus two OPTIONAL tagged segments
  ///   (`id:<installId>` and `capy:<assetName>`) that may appear anywhere
  ///   after the role but are canonically the LAST segments (see
  ///   [NdefRecord.badgePerson]).
  ///
  /// **Tagged-segment rules:**
  ///
  /// - A segment starting with `id:` sets [installId].
  /// - A segment starting with `capy:` sets [capybaraId].
  /// - A segment whose prefix is a known URI scheme (`http:`, `https:`,
  ///   `mailto:`, etc.) is treated as a URL and appended to [urls].
  /// - Any other segment matching `^[a-z][a-z0-9]*:` is an unknown tagged
  ///   segment and is **ignored** (forward-compatible: future v3 tags
  ///   won't pollute [urls]).
  /// - Anything else is treated as a URL and appended to [urls].
  ///
  /// A single-segment Text record is treated as a name-only payload.
  ///
  /// If no Text record is present, [name] and [role] are empty strings,
  /// [urls] is empty, and [installId]/[capybaraId] are `null`. If no URI
  /// record is present, [primaryUri] is `null`.
  factory BadgePerson.fromNdefMessage(NdefMessage message) {
    Uri? primaryUri;
    var name = '';
    var role = '';
    final urls = <String>[];
    String? installId;
    String? capybaraId;

    for (final record in message.records) {
      if (record.isUri && primaryUri == null) {
        try {
          primaryUri = record.decodeUri();
        } on FormatException {
          // Malformed U record — leave primaryUri null.
        }
      } else if (record.isText && name.isEmpty) {
        try {
          final decoded = record.decodeText();
          final segments = decoded.text.split(' · ');
          if (segments.isNotEmpty) {
            name = segments[0];
          }
          if (segments.length > 1) {
            role = segments[1];
          }
          if (segments.length > 2) {
            for (final segment in segments.sublist(2)) {
              if (segment.startsWith(_kInstallIdPrefix)) {
                installId = segment.substring(_kInstallIdPrefix.length);
              } else if (segment.startsWith(_kCapybaraPrefix)) {
                capybaraId = segment.substring(_kCapybaraPrefix.length);
              } else if (_isUnknownTaggedSegment(segment)) {
                // Unknown tagged segment — ignore for forward-compat.
                continue;
              } else {
                urls.add(segment);
              }
            }
          }
        } on FormatException {
          // Malformed T record — leave fields empty.
        }
      }
    }

    return BadgePerson(
      name: name,
      role: role,
      urls: List.unmodifiable(urls),
      primaryUri: primaryUri,
      installId: installId,
      capybaraId: capybaraId,
    );
  }

  /// The person's display name. Empty string if the badge carried no Text
  /// record.
  final String name;

  /// The person's role or title. Empty string if not present (or if the
  /// badge carried a name-only Text record).
  final String role;

  /// Any additional URLs found in the Text record, in order. May be empty.
  /// Tagged segments (`id:`, `capy:`, unknown `<tag>:`) are NOT included.
  final List<String> urls;

  /// The primary URL from the badge's U record. `null` if no U record is
  /// present or the record could not be parsed.
  final Uri? primaryUri;

  /// The badge owner's app install ID, from the `id:<installId>` tagged
  /// segment. `null` if the segment is absent.
  ///
  /// This is a random UUID generated by the app at first run; a reinstall
  /// produces a new ID. Nothing ties it back to anything except a specific
  /// installation at a specific point in time.
  final String? installId;

  /// The bundled capybara asset name (e.g. `"coffee_mode"`) when the badge
  /// image is a bundled capybara, from the `capy:<assetName>` tagged
  /// segment. `null` if the segment is absent (gallery images, or badges
  /// written before v2).
  final String? capybaraId;

  /// Tag prefix for the install-ID segment.
  static const String _kInstallIdPrefix = 'id:';

  /// Tag prefix for the capybara-asset segment.
  static const String _kCapybaraPrefix = 'capy:';

  /// Matches any lowercase alphanumeric tag prefix of the form `<tag>:`
  /// (e.g. `id:`, `capy:`, `v3:`, `https:`). Used to extract the tag so the
  /// decoder can distinguish unknown tagged segments (ignored) from URLs
  /// with schemes (kept).
  static final RegExp _kTaggedSegmentPattern = RegExp('^([a-z][a-z0-9]*):');

  /// URI schemes that appear in user-supplied URLs and must NOT be treated
  /// as unknown tags. Mirrors the well-known prefixes in the NFC Forum URI
  /// RTD table, restricted to the schemes users actually type.
  static const Set<String> _kUriSchemes = {
    'http', 'https', 'tel', 'mailto', 'ftp', 'ftps', 'sftp', 'smb', 'nfs',
    'dav', 'news', 'telnet', 'imap', 'rtsp', 'urn', 'pop', 'sip', 'sips',
    'tftp', 'file',
  };

  /// True if [segment] starts with an unknown `<tag>:` prefix that should
  /// be silently ignored. False for `id:`, `capy:`, known URI schemes, and
  /// segments with no tag-like prefix.
  static bool _isUnknownTaggedSegment(String segment) {
    final match = _kTaggedSegmentPattern.firstMatch(segment);
    if (match == null) {
      return false;
    }
    final tag = match.group(1)!;
    if (tag == 'id' || tag == 'capy') {
      return false; // known tags
    }
    if (_kUriSchemes.contains(tag)) {
      return false; // URI scheme, not a tag
    }
    return true; // unknown tag — ignore
  }

  @override
  String toString() => 'BadgePerson(name: "$name", role: "$role", '
      'urls: $urls, primaryUri: $primaryUri, '
      'installId: $installId, capybaraId: $capybaraId)';
}
